@url = http://localhost:3000/api/carrera
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYW5iZXJ0byIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzMzMDkxMjkxLCJleHAiOjE3MzMxNzc2OTF9.pjMMP2UrE4CLWIFp4Y7hpYqblvpup-0ZfOKM9YF6g-Y

###
GET {{url}}/

###
GET {{url}}/28

###
POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Tecnologias de la informacion",
  "nomenclatura": "TI",
  "nivel_educativo" : "TSU",
  "descripcion": "La carrera de Tecnologías de la Información se enfoca en el desarrollo y gestión de sistemas informáticos. Los estudiantes aprenden programación, redes y ciberseguridad, formando profesionales listos para enfrentar desafíos en un entorno digital en constante evolución."
}

###
PATCH {{url}}/28
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Artes y Humanidades patch",
  "areaDesarrolloIds": [1, 2, 20],
  "status": false
}

###
DELETE {{url}}/1


#carrera [Aptitudes{}, Area_Desarrollo{} ]

# PARA insertar una carrera la primera imagen siempre tiene que ser el icon y la segunda la imagen a cargar
###
POST {{url}}/
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token}}

--boundary
Content-Disposition: form-data; name="nombre"

Tecnologías de la Información
--boundary
Content-Disposition: form-data; name="nomenclatura"

TI
--boundary
Content-Disposition: form-data; name="nivel_educativo"

ING
--boundary
Content-Disposition: form-data; name="descripcion"

Un Ingeniero en Tecnologías de la Información (TI) se especializa en el diseño, desarrollo, implementación y gestión de sistemas informáticos y redes. Domina lenguajes de programación, bases de datos, ciberseguridad y soluciones tecnológicas, optimizando procesos empresariales y mejorando la eficiencia organizacional.
--boundary
Content-Disposition: form-data; name="images"; filename="TI.png"
Content-Type: image/jpeg

< C:\Users\newpr\Desktop\TI.png
--boundary
Content-Disposition: form-data; name="images"; filename="TI.png"
Content-Type: image/jpeg

< C:\Users\newpr\Downloads\Wallpapers-master\Wallpapers-master\21.jpg
--boundary--





# C:\Users\newpr\Desktop
###
# Areas TO CARRERA
POST {{url}}/assign-areas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "carreraId": 1,
  "areaDesarrolloIds": [1, 2, 3, 4]
}

###
# APTITUDES TO CARRERA
POST {{url}}/assign-aptitudes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "carreraId": 1,
  "aptitudesIds": [1, 2, 3, 4]
}