@url = http://localhost:3000/api/empresa
@empresa = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiZW1wcmVzYSIsInJvbCI6ImVtcHJlc2EiLCJpYXQiOjE3MzE0NzYwOTIsImV4cCI6MTczMTU2MjQ5Mn0.amn9-T9hCtISsUBBWFSyrsXXlN8lU2YixxVK2dnt-8E
@empresa2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJuYW1lIjoiZW1wcmVzYSAyIiwicm9sIjoiZW1wcmVzYSIsImlhdCI6MTczMTUyMjUxNywiZXhwIjoxNzMxNjA4OTE3fQ.bEpmqSEQgcTV5H0q9g5zJbQqLnH8zQj3fPLL13M1XSw
@admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYW5iZXJ0byIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzMxOTg5MzM0LCJleHAiOjE3MzIwNzU3MzR9.iF9Q-qsHOk04prt-pQ3k4YdiLhEaCK24Mpl2l7bxRkw
###
###
GET {{url}}/estadisticas
Authorization: Bearer {{admin}}

###
GET {{url}}/
Authorization: Bearer {{admin}}

###
POST {{url}}/
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Cervezas El Buen Sabor 2",
  "tipo": "Productora y distribuidora y otro",
  "giro": "Fabricación y comercialización de bebidas alcohólicas",
  "razon_social": "Cervezas El Buen Sabor, S.A. de C.V.",
  "sector": "Secundario",
  "direccion": {
    "calle": "Avenida de la Cerveza",
    "num_interior": "Apto 202",
    "num_exterior": "456",
    "colonia": "Zona Industrial",
    "municipio": "Guadalajara",
    "estado": "Jalisco",
    "pais": "México",
    "codigo_postal": 44500
  },
  "size": "Mediana",
  "alcance_geografico": "Nacional"
}


###
PATCH  {{url}}/direccion/1
Content-Type: application/json
Authorization: Bearer {{empresa}}

{
  "calle": "Cervezas 2"
}

###
PATCH {{url}}/1
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Red Osmo Enterprise"
}

###
DELETE {{url}}/4