@url = http://localhost:3000/api/empresa
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiYW5iZXJ0byIsInJvbCI6ImVtcHJlc2EiLCJpYXQiOjE3MzEwODgyMTEsImV4cCI6MTczMTE3NDYxMX0.W3nWPUl6xiZMg72UV1HhqDO9I7rNjx1BOB-tzeAiT_Q
@admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYW5iZXJ0byIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzMxMTE0NjE0LCJleHAiOjE3MzEyMDEwMTR9.yqFb54He6dmoJSQHoI66s_o6c2GJHmmzXZVD4JRXhYQ
###
###
GET {{url}}/
Authorization: Bearer {{admin}}

###
GET {{url}}/1
Authorization: Bearer {{admin}}

###
POST {{url}}/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Ejemplo Nombre",
  "tipo": "Tipo Ejemplo",
  "giro": "Giro Ejemplo",
  "razon_social": "Razón Social Ejemplo",
  "sector": "Primario",
  "direccion": {
    "calle": "Cervezas",
    "num_interior": "Selección de cervezas nacionales e internacionales",
    "num_exterior": "123",
    "colonia": "Centro",
    "municipio": "Municipio Ejemplo",
    "estado": "Estado Ejemplo",
    "pais": "México",
    "codigo_postal": 12345
  },
  "verificada": true,
  "size": "Mediana",
  "ubicacion": "Ubicación Ejemplo"
}

###
PATCH  {{url}}/direccion/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "calle": "Cervezas 2"
}

###
PATCH {{url}}/1
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Red Osmo Enterprise"
}

###
DELETE {{url}}/4