@url = http://localhost:3000/api/empresa
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiYW5iZXJ0byIsInJvbCI6ImVtcHJlc2EiLCJpYXQiOjE3MzEwODQxMjMsImV4cCI6MTczMTE3MDUyM30.YIKqWvn2aN3L4kbdVQD68saW708JBFykkWK_6Nz7wWM

###
###
GET {{url}}/

###
GET {{url}}/1

###
POST {{url}}/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Ejemplo Nombre",
  "tipo": "Tipo Ejemplo",
  "giro": "Giro Ejemplo",
  "razon_social": "Razón Social Ejemplo",
  "sector": "Primario",
  "direccion": {
    "calle": "Cervezas",
    "num_interior": "Selección de cervezas nacionales e internacionales",
    "num_exterior": "123",
    "colonia": "Centro",
    "municipio": "Municipio Ejemplo",
    "estado": "Estado Ejemplo",
    "pais": "México",
    "codigo_postal": 12345
  },
  "verificada": true,
  "size": "Mediana",
  "ubicacion": "Ubicación Ejemplo"
}

###
PATCH {{url}}/6
Content-Type: application/json

{
  "nombre": "Red Osmo"
}

###
DELETE {{url}}/4