@url = http://localhost:3000/api/habilidad
@admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYW5iZXJ0byIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzMxNTgwMDA0LCJleHAiOjE3MzE2NjY0MDR9.kAkit8fdz5i2gB3hfpIuWaTLzGXtsUci3MAdhL61yt4
###
GET {{url}}/
Authorization: Bearer {{admin}}

###
GET {{url}}/1

# Habilidades fuertes y blandas
###
POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Técnicas de cocina avanzada"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Gestión de cocina y equipo"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Control de calidad alimentaria"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Desarrollo de software"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Administración de bases de datos"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Ciberseguridad"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Programación de PLC"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Diseño de sistemas robóticos"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Sensores y actuadores"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Estrategia de negocios"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Negociación y comunicación efectiva"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Gestión de proyectos"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Energías renovables"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Eficiencia energética"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Gestión de proyectos de energía"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Trabajo en equipo"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Aprendizaje rápido"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Comunicación efectiva"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Resolución de problemas"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Liderazgo"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Adaptabilidad"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Gestión del tiempo"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Creatividad"
}

# ======================================================




###
PATCH {{url}}/1
Content-Type: application/json

{
  "calle": "calle de las rosas",
}

###
DELETE {{url}}/1


#carrera [Aptitudes{}, Area_Desarrollo{}, Nivel_Educativo]a