@url = http://localhost:3000/api/habilidad
@admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYW5iZXJ0byIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzMxODk0NTEyLCJleHAiOjE3MzE5ODA5MTJ9.QzszaXMeAVx4tBBCOkY7VP3sFkwoCwxcVjgRLyC8b6Q
@empresa= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiZW1wcmVzYSIsInJvbCI6ImVtcHJlc2EiLCJpYXQiOjE3MzE4OTA2ODcsImV4cCI6MTczMTk3NzA4N30.nOFsVlVl1CJAw2cAB8elOi5VOL7Extc0oHtI5QScIs0
###
GET {{url}}/
Authorization: Bearer {{empresa}}

###
GET {{url}}/1

# Habilidades fuertes y blandas
###
POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Programacion"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Gestión de cocina y equipo"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Control de calidad alimentaria"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Desarrollo de software"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Administración de bases de datos"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Ciberseguridad"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Programación de PLC"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Diseño de sistemas robóticos"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Sensores y actuadores"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Estrategia de negocios"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Negociación y comunicación efectiva"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Gestión de proyectos"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Energías renovables"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Eficiencia energética"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Gestión de proyectos de energía"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Trabajo en equipo"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Aprendizaje rápido"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Comunicación efectiva"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Resolución de problemas"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Liderazgo"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Adaptabilidad"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Gestión del tiempo"
}

###

POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "nombre": "Creatividad"
}

# ======================================================




###
PATCH {{url}}/1
Content-Type: application/json

{
  "calle": "calle de las rosas",
}

###
DELETE {{url}}/1


#carrera [Aptitudes{}, Area_Desarrollo{}, Nivel_Educativo]a