#INSTALAR LA EXTENSION DE REST CLIENT PARA UTILIZAR LAS PETICIONES
# REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nombre": "Ramses",
  "num_telefono": "+529513748375",
  "email": "ramsex@outlook.com",
  "password": "ramsesguapo"
}

# LOGIN
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "victorsjm@outlook.com",
  "pass": "quientepregunto03"
}
