#INSTALAR LA EXTENSION DE REST CLIENT PARA UTILIZAR LAS PETICIONES
# REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nombre": "anberto",
  "num_telefono": "+52 951 289 09 30",
  "email": "annn@gmail.com",
  "password": "12345678"
}

# LOGIN
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "annn@gmail.com",
  "pass": "12345678"
}

###
# USUARIO EMPRESA
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nombre": "empresa 2",
  "num_telefono": "+339512890932",
  "email": "empresa4@gmail.com",
  "password": "12345678",
  "cargo": "gerente",
  "area_trabajo": "recursos humanos"
}

# LOGIN EMPRESA
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "empresa@gmail.com",
  "pass": "12345678"
}


###
patch http://localhost:3000/api/user/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiZW1wcmVzYSIsInJvbCI6ImVtcHJlc2EiLCJpYXQiOjE3MzIyNjA4ODksImV4cCI6MTczMjM0NzI4OX0.G0K4HmD3Eg_CGW6j3fHT3yMetRGNZJmibXUEkIYNWrc

{
  "nombre": "Luis Mendoza Vasquez",
  "email": "empresa@gmail.com",
  "cargo": "gerente",
  "area_trabajo": "recursos humanos"
}