@url = http://localhost:3000/api/proyecto
@tokenEmpresa=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiZW1wcmVzYSIsInJvbCI6ImVtcHJlc2EiLCJpYXQiOjE3MzE4OTA2ODcsImV4cCI6MTczMTk3NzA4N30.nOFsVlVl1CJAw2cAB8elOi5VOL7Extc0oHtI5QScIs0

###
GET {{url}}/empresa/3
Authorization: Bearer {{tokenEmpresa}}

###
GET {{url}}/

###
POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{tokenEmpresa}}

{
  "nombre": "Desarrollo de App Móvil",
  "descripcion": "Este proyecto tiene como objetivo el desarrollo de una aplicación móvil para gestionar tareas.",
  "participantes_requeridos": "",
  "habilidades_ids": [1, 2, 3, 4],
  "empresa_id": 1,
  "carrera_id": 4
}
###
POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{tokenEmpresa}}

{
  "nombre": "Desarrollo de un Robot Autónomo para Inspección Industrial",
  "descripcion": "Este proyecto tiene como objetivo el diseño y la construcción de un robot autónomo capaz de realizar inspecciones en entornos industriales. El robot utilizará sensores de proximidad y cámaras para detectar fallas en máquinas y equipos, y enviará los datos recopilados a una plataforma para su análisis y mantenimiento preventivo.",
  "participantes_requeridos": 3,
  "habilidades_ids": [8, 9, 16, 17],
  "empresa_id": 3,
  "carrera_id": 1
}


###
PATCH {{url}}/
Content-Type: application/json

{
  "status": false
}

###
DELETE {{url}}/1