@url = http://localhost:3000/api/proyecto
@tokenEmpresa=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYW5iZXJ0byIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzMzMDg2MjQ2LCJleHAiOjE3MzMxNzI2NDZ9.elKvt_QmHJr4X8FKXtsv2zrJhtxz1Jj34aZuBYL13ko

###
GET {{url}}/empresa/3
Authorization: Bearer {{tokenEmpresa}}

###
GET {{url}}/

###
POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{tokenEmpresa}}

{
    "nombre": "Desarrollo de una Interfaz Web Intuitiva",
    "descripcion": "Este proyecto tiene como objetivo que el estudiante demuestre sus habilidades tanto en el diseño de interfaces como en el desarrollo frontend. El estudiante deberá crear una interfaz web moderna, funcional y fácil de usar para un sistema de gestión, que pueda ser utilizada para gestionar datos de usuarios, productos o cualquier tipo de información que sea relevante. El enfoque principal del proyecto es la experiencia de usuario (UX) y la implementación de un diseño limpio, accesible y adaptado a dispositivos móviles.",
    "participantes_requeridos": "",
    "carrera_id": 4,
    "habilidades_ids": [
        23,
        25,
        16
    ],
    "empresa_id": 1
}

# {
#   "nombre": "Desarrollo de App Móvil",
#   "descripcion": "Este proyecto tiene como objetivo el desarrollo de una aplicación móvil para gestionar tareas.",
#   "participantes_requeridos": 5,
#   "habilidades_ids": [1, 2, 3, 4],
#   "empresa_id": 1,
#   "carrera_id": 4
# }
###
POST {{url}}/ 
Content-Type: application/json
Authorization: Bearer {{tokenEmpresa}}

{
  "nombre": "Desarrollo de un Robot Autónomo para Inspección Industrial",
  "descripcion": "Este proyecto tiene como objetivo el diseño y la construcción de un robot autónomo capaz de realizar inspecciones en entornos industriales. El robot utilizará sensores de proximidad y cámaras para detectar fallas en máquinas y equipos, y enviará los datos recopilados a una plataforma para su análisis y mantenimiento preventivo.",
  "participantes_requeridos": 3,
  "habilidades_ids": [8, 9, 16, 17],
  "empresa_id": 3,
  "carrera_id": 1
}



###
PATCH {{url}}/1/status
Authorization: Bearer {{tokenEmpresa}}
Content-Type: application/json

{
  "status": "rechazado"
}

###
DELETE {{url}}/empresa/1/10
Authorization: Bearer {{tokenEmpresa}}